# PostgreSQL. Versions 9.3 and up are supported.
# Install the pg driver:
#   gem install pg

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ysmen_crm_development

test:
  <<: *default
  database: ysmen_crm_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
